networks:
  serv:

version: '1.01'

services:
  chatbot1:
    build: ./app
    environment:
      - PORT=8501
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "main.py", "--server.port=8501"]
    networks:
      - serv

  chatbot2:
    build: ./app
    environment:
      - PORT=8502
    ports:
      - "8502:8501"
    command: ["streamlit", "run", "main.py", "--server.port=8502"]
    networks:
      - serv

  nginx:
    image: nginx:stable-alpine
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatbot1
      - chatbot2
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - serv